name: Build and Run AiCodeReviewer By Main Maven Jar

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - '*' 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 优化拉取深度

      - name: Setup JDK 11
        uses: actions/setup-java@v3  # 升级到 v3
        with:
          distribution: 'temurin'  # 推荐使用 Temurin
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy JAR from target directory
        run: |
          mkdir -p ./libs
          cp target/*.jar ./libs/  # 从 target 目录复制 JAR 文件

      - name: Run code Review
        run: |
          JAR_FILE=$(ls ./libs/*.jar)  # 动态获取 JAR 文件名
          java -jar $JAR_FILE
